# Generated by Django 5.1.6 on 2025-02-22 21:00
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="todo_list",
            new_name="list",
        ),
    ]
